---
- name: Install LAP services
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php5-mysql
   - php5
   - libapache2-mod-php5
   - php5-mcrypt
   - php5-gd
   - libssh2-php

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 

- name: Extract WordPress 
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no 

- name: Update default Apache site
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
   dest=/var/www/wordpress/wp-config.php
   regexp="{{ item.regexp }}"
   line="{{ item.line }}"
  with_items:
   - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{ groups['database'][0] }}');"}
   - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ hostvars[groups['database'][0]]['wp_mysql_db'] }}');"}
   - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ hostvars[groups['database'][0]]['wp_mysql_user'] }}');"}
   - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ hostvars[groups['database'][0]]['wp_mysql_password'] }}');"}
